### PR TITLE
make Search endpoints not error on empty search result and fix Search Channels

### LINKED ISSUE #92: Gettin `invalid type:null` with SearchCategories on no results
I tried to search for a term that does not exists, this results in the error below:

The Term I search was `Mitttttttttttt`

```
Error: HelixRequestGetError(DeserializeError("{\"data\":null,\"pagination\":{}}", Error("invalid type: null, expected a sequence", line: 1, column: 12), https://api.twitch.tv/helix/search/categories?query=Mitttttttttttt&first=20))
```

### PR DESCRIPTION
**Pull request by Emilgardis**
Search Categories returns a null value when the search is empty

Also corrects wrong path in Search Channels

fixes #92

### CODE REVIEW

**Comment by Emilgardis** [comment]
search channels does the same...

File: src/helix/search/search_categories.rs [hunk 1]
```diff
@@ -74,7 +76,46 @@ impl Request for SearchCategoriesRequest {
...
+        }) = serde_json::from_str::<helix::HelixRequestError>(&text)
+        {
+            return Err(helix::HelixRequestGetError::Error {
+                error,
+                status: status.try_into().unwrap_or(http::StatusCode::BAD_REQUEST),
+                message,
+                uri: uri.clone(),
+            });
+        }
+        let response: helix::InnerResponse<Option<_>> =
```
Comment (Emilgardis) [inline src/helix/search/search_categories.rs:108]: Think I want to look over the possibility of replacing `HelixRequestError` and `InnerResponse` as deser targets for less code-duplication.
